# Generated by Django 3.0.8 on 2020-07-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Missions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(db_index=True, max_length=500, verbose_name='Mission')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is completed ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
